#!/usr/bin/env python

# Archipelago, a multi-user dungeon (MUD) server, by Martin Keegan
#
# Copyright (C) 2009-2012  Martin Keegan
#
# This programme is free software; you may redistribute and/or modify
# it under the terms of the GNU Affero General Public Licence as published by
# the Free Software Foundation, either version 3 of said Licence, or
# (at your option) any later version.

import sys
import curses
import curses.ascii
import curses.wrapper

from Multiplexer import Multiplexer
from Networking import Socket, zap_cr
from ServerLink import ServerLink
from SplitScreen import SplitScreen

server_address = ('localhost', 2500)

 
class Stdin(Socket):
    def __init__(self):
        super(Stdin, self).__init__(sys.stdin, None)

class SSFE(Stdin):
    def __init__(self, ss=None, **kwargs):
        super(SSFE, self).__init__()
        self.ss = ss

    def handleReadable(self):
        self.ss.handle_input()


def main(stdscr):
    ss = SplitScreen(stdscr)
    ss.setup()
    ss.write_prompt()

    server = ServerLink(server_address, ss=ss)

    if server.connection_failed:
        return server.connection_failed

    stdin = SSFE(ss=ss)

    ss.set_server_link(server)

    if not server.connection_failed:
        m = Multiplexer()
        m.addSocket(server)
        m.addSocket(stdin)
        m.run()
    ss.shutdown()
    return ""

def run():
    curses.wrapper(main)

def run_alt():
    import os

    stdscr = curses.initscr()
    curses.noecho()
    curses.cbreak()
    stdscr.keypad(True)
    try:
        msg = ""
        msg = main(stdscr)
    finally:
        curses.nocbreak()
        stdscr.keypad(False)
        curses.echo()
        os.system("stty sane") # screw you, ncurses
        print "\r" + msg

if __name__ == '__main__':
    run_alt()
