
OCAMLFLAGS := -rectypes -g -w Aez -warn-error Aez
OCAMLLDFLAGS := -rectypes -g
ANNOTATE := yes

LIBS := str

SOURCES := utils.ml fsm.ml

RESULT := general

all: byte-code-library
include OCamlMakefile


